import { AsyncLocalStorage } from "node:async_hooks";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { type Client, createClient } from "@libsql/client";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";

import { getDatabaseConfig } from "./db-config";
import { isBusyError } from "./errors";
import * as providerMappingSchema from "./provider-mapping-schema";
import * as coreSchema from "./schema";

const SYNC_LEASE_HEARTBEAT_MS = 60_000;
const SYNC_LEASE_STALE_MS = 5 * 60_000;

/** Generated by `bun run db:generate`; applied automatically when the database is first opened. */
const MIGRATIONS_FOLDER = fileURLToPath(new URL("../drizzle", import.meta.url));

const BUSY_RETRY_LIMIT_MS = 30_000;
const BUSY_RETRY_MAX_DELAY_MS = 100;

const schema = {
  ...coreSchema,
  ...providerMappingSchema,
};

let clientInstance: Client | null = null;
let dbInstance: ReturnType<typeof createDb> | null = null;

/**
 * Retries an operation that failed because another connection holds the
 * write lock.
 *
 * SQLite allows one writer at a time, and libsql gives each open transaction
 * its own connection, so a write that lands while a transaction (in this
 * process or in the sync child process) is open fails with SQLITE_BUSY. The
 * driver's own busy timeout would wait synchronously and block the event
 * loop — deadlocking against an in-process transaction that needs the loop to
 * finish — so the wait happens here, asynchronously. A busy statement never
 * executed, so retrying it is safe.
 */
async function retryWhileBusy<T>(operation: () => Promise<T>): Promise<T> {
  const deadline = Date.now() + BUSY_RETRY_LIMIT_MS;
  for (let attempt = 0; ; attempt++) {
    try {
      return await operation();
    } catch (error) {
      if (!isBusyError(error) || Date.now() > deadline) throw error;
      await Bun.sleep(Math.min(2 ** attempt, BUSY_RETRY_MAX_DELAY_MS));
    }
  }
}

/** FIFO async mutex. */
class AsyncLock {
  #tail: Promise<void> = Promise.resolve();

  acquire(): Promise<() => void> {
    let release!: () => void;
    const released = new Promise<void>((resolve) => {
      release = resolve;
    });
    const previous = this.#tail;
    this.#tail = previous.then(() => released);
    return previous.then(() => release);
  }
}

/**
 * Serialises database access within this process. SQLite has a single
 * writer, so this costs little, and it keeps concurrent transactions from
 * interleaving across libsql's pooled connections, which left later commits
 * failing with "SQL statements in progress". A transaction holds the lock for
 * its whole callback; anything issued from inside that callback, even through
 * the global `db` rather than `tx`, bypasses it instead of deadlocking.
 */
const processLock = new AsyncLock();
const insideTransaction = new AsyncLocalStorage<boolean>();

async function withProcessLock<T>(operation: () => Promise<T>): Promise<T> {
  if (insideTransaction.getStore()) return operation();
  const release = await processLock.acquire();
  try {
    return await operation();
  } finally {
    release();
  }
}

/**
 * Wraps the client so every entry point waits for `ready` (WAL + migrations),
 * takes the process lock, and retries on SQLITE_BUSY, which still covers
 * other processes such as the sync child process. `transaction` is locked one
 * level up, around the whole drizzle callback (see {@link createDb}).
 */
function wrapClient(raw: Client, ready: Promise<void>): Client {
  const guarded = new Set<PropertyKey>(["execute", "batch", "migrate", "executeMultiple"]);
  return new Proxy(raw, {
    get(target, property) {
      const value = Reflect.get(target, property, target);
      if (typeof value !== "function") return value;
      if (property === "transaction") {
        return async (...args: unknown[]) => {
          await ready;
          return retryWhileBusy(() => value.apply(target, args));
        };
      }
      if (!guarded.has(property)) return value.bind(target);
      return async (...args: unknown[]) => {
        await ready;
        return withProcessLock(() => retryWhileBusy(() => value.apply(target, args)));
      };
    },
  });
}

async function prepareDatabase(raw: Client): Promise<void> {
  // WAL lets readers proceed while a writer is mid-transaction; the setting
  // is stored in the database file, so it applies to every later connection.
  await retryWhileBusy(() => raw.execute("PRAGMA journal_mode = WAL"));
  await retryWhileBusy(() => migrate(drizzle(raw), { migrationsFolder: MIGRATIONS_FOLDER }));
}

function getClient(): Client {
  if (!clientInstance) {
    const { url, path } = getDatabaseConfig();
    mkdirSync(dirname(path), { recursive: true });
    const raw = createClient({ url });
    const ready = prepareDatabase(raw);
    // Surface failures through the first query rather than as an unhandled rejection.
    ready.catch(() => {});
    clientInstance = wrapClient(raw, ready);
  }
  return clientInstance;
}

function createDb() {
  const instance = drizzle(getClient(), { schema });
  const transaction = instance.transaction.bind(instance);
  instance.transaction = ((callback, config) =>
    insideTransaction.getStore()
      ? transaction(callback, config)
      : withProcessLock(() =>
          insideTransaction.run(true, () => transaction(callback, config)),
        )) as typeof instance.transaction;
  return instance;
}

function getDb(): ReturnType<typeof createDb> {
  if (!dbInstance) {
    dbInstance = createDb();
  }
  return dbInstance;
}

/**
 * Validates database configuration without opening the database.
 *
 * The client is created lazily so that importing this module stays free of
 * side effects — otherwise any module that transitively imports `@anicore/db`
 * would create a database file, including unit tests of pure helpers.
 * Long-lived entrypoints call this at startup to fail fast on a bad
 * DATABASE_URL.
 */
export function assertDatabaseConfigured(): void {
  getDatabaseConfig();
}

/** Opens the database and applies any pending migrations. */
export async function migrateDatabase(): Promise<void> {
  await getDb().run(sql`select 1`);
}

export const db = new Proxy({} as ReturnType<typeof createDb>, {
  get(_target, property) {
    const instance = getDb() as unknown as Record<string | symbol, unknown>;
    const value = instance[property];
    return typeof value === "function" ? value.bind(instance) : value;
  },
  has(_target, property) {
    return property in (getDb() as object);
  },
});

export type Db = typeof db;
export interface SyncLease {
  release(succeeded?: boolean): Promise<void>;
}

export async function tryAcquireSyncLease(): Promise<SyncLease | null> {
  const token = randomUUID();
  // Raw `get` crashes in drizzle's libsql driver when no row matches, so
  // single-row reads use `all` and take the first element.
  // The write transaction (BEGIN IMMEDIATE) serialises lease acquisition
  // across processes, which the Postgres version did with LOCK TABLE.
  const leaseId = await getDb().transaction(async (tx) => {
    const now = Date.now();
    await tx.run(sql`
      UPDATE sync_runs
      SET status = 'failed',
        finished_at = ${now},
        error_message = 'Recovered stale sync lease'
      WHERE provider = 'anilist'
        AND kind = 'full'
        AND status = 'running'
        AND COALESCE(json_extract(metadata_json, '$.heartbeatAt'), started_at) < ${now - SYNC_LEASE_STALE_MS}
    `);
    const [active] = await tx.all<{ id: number }>(sql`
      SELECT id
      FROM sync_runs
      WHERE provider = 'anilist'
        AND kind = 'full'
        AND status = 'running'
      LIMIT 1
    `);
    if (active) return null;

    const [inserted] = await tx.all<{ id: number }>(sql`
      INSERT INTO sync_runs (provider, kind, status, metadata_json)
      VALUES (
        'anilist',
        'full',
        'running',
        ${JSON.stringify({ leaseToken: token, heartbeatAt: now })}
      )
      RETURNING id
    `);
    return inserted?.id ?? null;
  });

  if (leaseId === null) return null;

  const heartbeat = setInterval(() => {
    void getDb()
      .run(sql`
        UPDATE sync_runs
        SET metadata_json = json_set(metadata_json, '$.heartbeatAt', ${Date.now()})
        WHERE id = ${leaseId}
          AND status = 'running'
      `)
      .catch((error) =>
        console.error(
          JSON.stringify({
            event: "sync.lease_heartbeat.failed",
            err: error instanceof Error ? error.message : String(error),
          }),
        ),
      );
  }, SYNC_LEASE_HEARTBEAT_MS);
  heartbeat.unref?.();

  let released = false;
  return {
    async release(succeeded = true): Promise<void> {
      if (released) return;
      released = true;
      clearInterval(heartbeat);
      await getDb().run(sql`
        UPDATE sync_runs
        SET status = ${succeeded ? "success" : "failed"},
          finished_at = ${Date.now()},
          error_message = ${succeeded ? null : "Sync process failed"}
        WHERE id = ${leaseId}
          AND status = 'running'
      `);
    },
  };
}

export async function closeDb(): Promise<void> {
  if (!clientInstance) return;
  clientInstance.close();
  clientInstance = null;
  dbInstance = null;
}
